FROM openjdk:17.0.1-jdk-slim

MAINTAINER sph.com

COPY target/NotificationService-0.0.1-SNAPSHOT.jar NotificationService-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","NotificationService-0.0.1-SNAPSHOT.jar"]