FROM openjdk:17.0.1-jdk-slim

MAINTAINER sph.com

COPY target/ShoppersHubUtilities-0.0.1-SNAPSHOT.jar ShoppersHubUtilities-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","ShoppersHubUtilities-0.0.1-SNAPSHOT.jar"]