FROM openjdk:17.0.1-jdk-slim

MAINTAINER sph.com

COPY target/ShoppersHubServiceRegistery-0.0.1-SNAPSHOT.jar ShoppersHubServiceRegistery-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","ShoppersHubServiceRegistery-0.0.1-SNAPSHOT.jar"]