package com.sph.book.dto;

import java.time.Instant;

import com.sph.util.model.Address;
import com.sph.util.model.PaymentStatus;
import com.sph.util.model.PaymentType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ReceiptDto {

	
	 private String receiptId;

	    private String bookingId;
	    private String userId;

	    private PaymentType paymentType;
	    private PaymentStatus paymentStatus;
	    private String paymentTransactionId;//autogenerated by payment gateway
	    
	    private int itemQuantity;
	    private double itemPrice;
	    private double taxAmount;
	    private double deliveryCharge;
	    private double totalAmount;

	    private Address billingAddress;
	    private Address deliveryAddress;

	    private Instant generatedAt; //autogenerated timestamp
}
